### ISSUE TITLE
[Bug] `pyenv` Permission denied

### ISSUE THREAD

**Issue by cqw-acq** [RubyMetric/chsrc#95]
### 你操作了什么？

chsrc set pip

### 发生了什么？

没有成功

### 本应该怎么样？

希望成功还原

### chsrc 版本

chsrc: Change Source (GPLv3+) v0.1.8.2-2024/09/10 by RubyMetric

### 你使用的是哪个操作系统？

macOS

### OS 版本 / OS 发行版

14.4

### Log 输出

```shell
ERROR: Unable to save configuration. Please report this as a bug.
Traceback (most recent call last):
  File "/Users/chuqi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pip/_internal/commands/configuration.py", line 265, in _save_configuration
    self.configuration.save()
  File "/Users/chuqi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pip/_internal/configuration.py", line 211, in save
    ensure_dir(os.path.dirname(fname))
  File "/Users/chuqi/.pyenv/versions/3.11.0/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 104, in ensure_dir
    os.makedirs(path)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/Users/chuqi/.config/pip'
ERROR: Internal Error.
[chsrc 运行] x 命令执行失败，退出状态: 256
chsrc: 关键错误，强制结束
```

### 防止重复问题

- [X] 我已在项目的 GitHub 和 Gitee 两个仓库分别搜索过类似的 issue

**Comment by ccmywish** [comment]
加个 `sudo` 试试

**Comment by ccmywish** [comment]
若依然有问题，可重新打开 issue 或 发新的 issue
